const galleryData = {
  hero: {
    title: "Our Gallery",
    subtitle: "Moments at Hookah69",
    description: "Take a visual journey through our premium lounge experience",
  },

  categories: [
    { id: "all", name: "All", count: 24 },
    { id: "ambience", name: "Ambience", count: 8 },
    { id: "hookah", name: "Hookah", count: 6 },
    { id: "cocktails", name: "Cocktails", count: 5 },
    { id: "events", name: "Events", count: 3 },
    { id: "food", name: "Food", count: 2 },
  ],

  items: [
    // Ambience Images
    {
      id: 1,
      type: "image",
      category: "ambience",
      title: "Main Lounge Area",
      description: "Our luxurious main lounge with mountain views",
      image: "/gallery/photo/hookah.jpeg",
      thumbnail: "/gallery/photo/hookah.jpeg",
      date: "2024-02-15",
      featured: true,
    },
    {
      id: 2,
      type: "image",
      category: "ambience",
      title: "VIP Section",
      description: "Exclusive VIP area for private gatherings",
      image: "/gallery/photo/hookah.PNG",
      thumbnail: "/gallery/photo/hookah.PNG",
      date: "2024-02-10",
      featured: true,
    },
    {
      id: 3,
      type: "image",
      category: "ambience",
      title: "Outdoor Seating",
      description: "Beautiful outdoor space with lakeside views",
      image: "/gallery/photo/premiun hookah.jpeg",
      thumbnail: "/gallery/photo/premiun hookah.jpeg",
      date: "2024-02-05",
    },
    {
      id: 4,
      type: "image",
      category: "ambience",
      title: "Sunset View",
      description: "Stunning sunset views from our lounge",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-01-28",
    },
    {
      id: 5,
      type: "image",
      category: "ambience",
      title: "Night Atmosphere",
      description: "The lounge comes alive at night",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-01-20",
    },
    {
      id: 6,
      type: "image",
      category: "ambience",
      title: "Bar Counter",
      description: "Our elegant bar with premium spirits",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-01-15",
    },
    {
      id: 7,
      type: "image",
      category: "ambience",
      title: "Cozy Corners",
      description: "Intimate seating areas for small groups",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-01-10",
    },
    {
      id: 8,
      type: "image",
      category: "ambience",
      title: "Mountain View",
      description: "Panoramic views of the Himalayas",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-01-05",
    },

    // Hookah Images
    {
      id: 9,
      type: "image",
      category: "hookah",
      title: "Premium Hookah Setup",
      description: "Our signature hookah with fresh fruits",
      image: "/gallery/photo/premiun hookah.jpeg",
      thumbnail: "/gallery/photo/premiun hookah.jpeg",
      date: "2024-02-12",
      featured: true,
    },
    {
      id: 10,
      type: "image",
      category: "hookah",
      title: "Hookah Preparation",
      description: "Expert preparation of premium blends",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-02-08",
    },
    {
      id: 11,
      type: "image",
      category: "hookah",
      title: "Fruit Hookah",
      description: "Fresh fruit hookah with ice base",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-02-01",
    },
    {
      id: 12,
      type: "image",
      category: "hookah",
      title: "Hookah Collection",
      description: "Our premium hookah collection",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-01-25",
    },
    {
      id: 13,
      type: "image",
      category: "hookah",
      title: "Flavor Selection",
      description: "Wide variety of premium flavors",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-01-18",
    },
    {
      id: 14,
      type: "image",
      category: "hookah",
      title: "Hookah Night",
      description: "Perfect evening with friends",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-01-12",
    },

    {
      id: 16,
      type: "image",
      category: "cocktails",
      title: "Cocktail Collection",
      description: "Artfully crafted cocktails",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-02-09",
    },
    {
      id: 17,
      type: "image",
      category: "cocktails",
      title: "Mixology Art",
      description: "Our master mixologists at work",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-02-03",
    },
    {
      id: 18,
      type: "image",
      category: "cocktails",
      title: "Cocktail Presentation",
      description: "Beautifully presented drinks",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-01-22",
    },
    {
      id: 19,
      type: "image",
      category: "cocktails",
      title: "Mocktail Delights",
      description: "Refreshing non-alcoholic options",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-01-17",
    },

    // Events Images
    {
      id: 20,
      type: "image",
      category: "events",
      title: "Live Music Night",
      description: "Talented artists performing live",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-02-11",
      featured: true,
    },
    {
      id: 21,
      type: "image",
      category: "events",
      title: "Birthday Celebration",
      description: "Special moments with loved ones",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-02-04",
    },
    {
      id: 22,
      type: "image",
      category: "events",
      title: "New Year's Eve",
      description: "Ring in the new year in style",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-01-01",
    },

    // Food Images
    {
      id: 23,
      type: "image",
      category: "food",
      title: "Gourmet Platters",
      description: "Delicious food pairings",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-02-07",
    },
    {
      id: 24,
      type: "image",
      category: "food",
      title: "Small Plates",
      description: "Perfect appetizers for sharing",
      image: "/hookah/logo.jpg",
      thumbnail: "/hookah/logo.jpg",
      date: "2024-01-30",
    },

    // Videos
    {
      id: 25,
      type: "video",
      category: "events",
      title: "Live DJ Performance",
      description: "Experience the energy of our live DJ nights",
      videoId: "dQw4w9WgXcQ", // Replace with actual YouTube ID
      thumbnail: "/hookah/logo.jpg",
      duration: "2:30",
      date: "2024-02-13",
      featured: true,
    },
    {
      id: 26,
      type: "video",
      category: "hookah",
      title: "Hookah Making Process",
      description: "Watch how we prepare the perfect hookah",
      videoId: "dQw4w9WgXcQ", // Replace with actual YouTube ID
      thumbnail: "/hookah/logo.jpg",
      duration: "1:45",
      date: "2024-02-06",
    },
    {
      id: 27,
      type: "video",
      category: "cocktails",
      title: "Cocktail Mixology",
      description: "Our mixologist creates signature drinks",
      videoId: "dQw4w9WgXcQ", // Replace with actual YouTube ID
      thumbnail: "/hookah/logo.jpg",
      duration: "3:15",
      date: "2024-01-27",
    },
    {
      id: 28,
      type: "video",
      category: "ambience",
      title: "Sunset at Hookah69",
      description: "Beautiful sunset views from our lounge",
      videoId: "dQw4w9WgXcQ", // Replace with actual YouTube ID
      thumbnail: "/hookah/logo.jpg",
      duration: "1:20",
      date: "2024-01-19",
    },
  ],
};

export default galleryData;
