export const drinksMenu = {
  espresso: [
    { name: "Espresso", price: "120" },
    { name: "Doppio", price: "180" },
    { name: "Espresso Afagato", price: "200" },
    { name: "Espresso Macchiato", price: "150" },
    { name: "Americano", price: "150" },
    { name: "Cafe Latte", price: "180" },
    { name: "Cafe Mocha", price: "200" },
    { name: "Honey Latte", price: "200" },
  ],
  frappe: [
    { name: "Blended Choco Mint Frappe", price: "400" },
    { name: "Blended Oreo Frappe", price: "350" },
    { name: "Blended Strawberry Frappe", price: "350" },
    { name: "Blended Mocha Frappe", price: "350" },
  ],
  milkshakes: [
    { name: "Chocolate Milkshake", price: "210" },
    { name: "Strawberry Milkshake", price: "210" },
    { name: "Vanilla Milkshake", price: "210" },
    { name: "Oreo Milkshake", price: "250" },
    { name: "Banana Milkshake", price: "250" },
  ],
  flavorTea: [
    { name: "Green Tea", price: "100" },
    { name: "Mint Tea", price: "120" },
    { name: "Peach Tea", price: "120" },
    { name: "Masala Tea", price: "100" },
    { name: "Milk Tea", price: "80" },
    { name: "Lemon Tea", price: "60" },
    { name: "Black Tea", price: "50" },
  ],
  coffeeAlternative: [
    { name: "Hot Chocolate", price: "180" },
    { name: "Honey Hot Lemon", price: "150" },
    { name: "Hot Lemon With Ginger Honey", price: "160" },
    { name: "Fresh Mint Lemonade", price: "250" },
    { name: "ICE Lemonade", price: "200" },
    { name: "Peach Ice Tea", price: "170" },
    { name: "Apple Ice Tea", price: "170" },
    { name: "Lemon Ice Tea", price: "170" },
  ],
  lassi: [
    { name: "Banana Lassi", price: "210" },
    { name: "Mango Lassi", price: "230" },
    { name: "Mix Fruits Lassi", price: "250" },
    { name: "Sweet Lassi", price: "170" },
    { name: "Plain Lassi", price: "170" },
  ],
  juice: [
    { name: "Watermelon", price: "180" },
    { name: "Pineapple", price: "180" },
    { name: "Orange", price: "180" },
    { name: "Apple", price: "180" },
    { name: "Litchi", price: "180" },
    { name: "Cranberry", price: "180" },
  ],
  mocktails: [
    { name: "Cranberry Cooler", price: "350" },
    { name: "Cinderella", price: "350" },
    { name: "Shirley Temple", price: "350" },
  ],
  spirits: [
    { name: "Old Durbar Regular", price: "175", bottle: "4000" },
    { name: "Old Durbar (Black Chimney)", price: "200", bottle: "4500" },
    { name: "G&G", price: "180", bottle: "4100" },
    { name: "Khukuri Rum XXX", price: "140", bottle: "3000" },
    { name: "Black Label", price: "450", bottle: "10000" },
    { name: "Double Black", price: "500", bottle: "12000" },
    { name: "Chivas 12 Years", price: "400", bottle: "9000" },
    { name: "Jameson", price: "400", bottle: "9000" },
    { name: "Jack Daniels", price: "400", bottle: "9000" },
    { name: "Absolute Vodka", price: "375", bottle: "8500" },
    { name: "8848 Vodka", price: "140", bottle: "3000" },
    { name: "Bombay Sapphire", price: "500", bottle: "12000" },
    { name: "Snow Man", price: "130", bottle: "2800" },
  ],
  shots: [
    { name: "Taquila Gold", price: "599" },
    { name: "Taquila Silver", price: "599" },
    { name: "Jagermeister", price: "500" },
    { name: "Baileys", price: "599" },
  ],
  beers: [
    { name: "Tuborg", price: "550" },
    { name: "Gorkha", price: "500" },
    { name: "Barsinghe (Pilsner)", price: "590" },
  ],
  wine: [
    { name: "Bigmaster", glass: "280", bottle: "1300" },
    { name: "Manang Valley", glass: "300", bottle: "1500" },
    { name: "Porto", glass: "700", bottle: "3500" },
  ],
  smoke: [
    { name: "69 Premium Hookah (Mint/Paan/Blueberry/1001)", price: "750" },
    { name: "Luxury Pot Hookah (Mint/Paan/Blueberry/1001)", price: "1050" },
    { name: "Cigarettes", price: "30 (Per Pcs.)" },
  ],
};

export const snacksMenu = {
  soup: [
    { name: "Clear Soup", veg: "160", chicken: "220" },
    { name: "Hot & Sour", veg: "210", chicken: "260" },
  ],
  salad: [
    { name: "Green Salad", price: "180" },
    { name: "Fruits Salad", price: "210" },
    { name: "Chef Special Salad", price: "320" },
  ],
  sekuwa: [
    { name: "Chicken Sekuwa", price: "360" },
    { name: "Buff Sekuwa", price: "380" },
    { name: "Pork Sekuwa", price: "420" },
  ],
  nonVegSnacks: [
    { name: "Timur Chicken", price: "350" },
    { name: "Chicken Chilly", price: "290" },
    { name: "Chicken Nuggets", price: "340" },
    { name: "Chicken Sadheko", price: "270" },
    { name: "Fish Finger", price: "310" },
    { name: "Buff Chilly", price: "280" },
    { name: "Sukuti Sadheko", price: "250" },
    { name: "Buff Chhoila", price: "220" },
    { name: "Buff Chhoila Set", price: "280" },
  ],
  sausage: [
    { name: "Chicken Sausage", boil: "190", fry: "220" },
    { name: "Buff Sausage", boil: "180", fry: "210" },
  ],
  burger: [
    { name: "Chicken Crispy Burger", price: "270" },
    { name: "Veg-Burger", price: "210" },
    { name: "Chef Special Burger", price: "320" },
  ],
  sandwich: [
    { name: "Chicken Sandwich", price: "270" },
    { name: "Veg-Sandwich", price: "210" },
    { name: "Club Sandwich", price: "370" },
  ],
  keemaNoodles: [
    { name: "Chicken Keema Noodles", price: "220" },
    { name: "Buff Keema Noodles", price: "200" },
  ],
  sizzler: [
    { name: "Chicken Sizzler", price: "460" },
    { name: "Veg-Sizzler", price: "370" },
    { name: "Sizzling Brownie", price: "230" },
  ],
  vegSnacks: [
    { name: "Mustang Aalu", price: "290" },
    { name: "Crispy Corn", price: "280" },
    { name: "Golden Fry Mushroom", price: "290" },
    { name: "Paneer Pakoda", price: "320" },
    { name: "Chips Chilly", price: "210" },
    { name: "Paneer Chilly", price: "320" },
    { name: "Wai-Wai Sadheko", price: "150" },
    { name: "Mushroom Salt & Pepper", price: "300" },
    { name: "French Fry", price: "170" },
    { name: "Fresh Mushroom Fry", price: "270" },
    { name: "Chatpate", price: "160" },
  ],
  momo: [
    { name: "Steam", veg: "160", chicken: "190", buff: "190" },
    { name: "Kothey", veg: "180", chicken: "210", buff: "210" },
    { name: "Jhol", veg: "210", chicken: "240", buff: "240" },
    { name: "Crispy", veg: "220", chicken: "250", buff: "250" },
    { name: "Chilly", veg: "240", chicken: "270", buff: "275" },
  ],
  chowmein: [
    { name: "Veg", price: "160" },
    { name: "Chicken", price: "190" },
    { name: "Buff", price: "190" },
    { name: "Mix", price: "210" },
    { name: "Egg", price: "180" },
  ],
  thukpa: [
    { name: "Veg", price: "180" },
    { name: "Chicken", price: "210" },
    { name: "Buff", price: "210" },
    { name: "Mix", price: "230" },
    { name: "Egg", price: "200" },
  ],
  fryRice: [
    { name: "Veg", price: "170" },
    { name: "Chicken", price: "200" },
    { name: "Buff", price: "200" },
    { name: "Mix", price: "220" },
    { name: "Egg", price: "190" },
  ],
  ramen: [
    { name: "Buldak Black", price: "370" },
    { name: "Buldak 2x Spicy", price: "370" },
    { name: "Shin Ramen", price: "320" },
    { name: "Current Noodles", price: "80" },
    { name: "With Omelette", price: "120" },
    { name: "Sausage (per piece)", price: "75" },
  ],
  pizza: [
    { name: "Margarita", small: "320", large: "530" },
    { name: "Vegetable", small: "370", large: "580" },
    { name: "Mushroom", small: "370", large: "580" },
    { name: "Chicken", small: "395", large: "595" },
    { name: "Mixed", small: "520", large: "680" },
    { name: "Meat Lover", small: "610", large: "800" },
  ],
  platters: [
    { name: "Non-Veg Platters", price: "690" },
    { name: "Momo Platters", price: "420" },
    { name: "Hakka Noodles", price: "260" },
    { name: "DUM-Biryani", price: "550" },
    { name: "Boiled Food Platters", price: "510" },
    { name: "Luxury Hookah", price: "1111" },
  ],
};
